hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
#hibernate.connection.url=jdbc:mysql://localhost:3306/elomyl?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
hibernate.connection.url=jdbc:mysql://localhost:3306/myldata?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
hibernate.connection.username=root
hibernate.connection.password=1234
hibernate.hbm2ddl.auto=update
hibernate.show_sql=false
hibernate.format_sql=true
hibernate.use_sql_comments=false
hibernate.jdbc.time_zone=America/Santiago
#hibernate.connection.pool_size=1

hibernate.connection.provider_class=org.hibernate.hikaricp.internal.HikariCPConnectionProvider
hibernate.hikari.connectionTimeout=10000
hibernate.hikari.minimumIdle=30
hibernate.hikari.maximumPoolSize=20
hibernate.hikari.idleTimeout=200000